### ISSUE TITLE
Resolving StartNSMCrossConnectServer from #490

### ISSUE THREAD

**Issue by edwarnicke** [ligato/networkservicemesh#506]
#490 is good work, I had one [point of discussion around StartNSMCrossConnectServer](https://github.com/ligato/networkservicemesh/pull/505#discussion_r234824285).  I'm going to go ahead and merge #490, and we can use this as a placeholder for coming to a conclusion on StartNSMCrossConnectServer and acting on that conclusion if it involves change.

**Comment by haiodo** [comment]
Sure, this make seance, will move StartNSMCrossConnectServer and make it internal inside nsmd, in case of multiple services will be available from NSMD via TCP it would have more seance for have one entry point for all calls. 

Also I Just think about "initial_transfer" in cross connects, I suppose we also need a "bulk update" in case of new dataplane arrives/re-connects, since it would generate a bunch of update events in NSMD to clients and more effective way would be to put them into one update event. @edwarnicke Thoughts?

Thanks.

**Comment by haiodo** [comment]
@edwarnicke Should we close this one already?
