### ISSUE TITLE
Create/send new NSM meeting time poll

### ISSUE THREAD

**Issue by lixuna** [ligato/networkservicemesh#97]
Action item: Send a follow-up poll to select the preferred NSM meeting time

Requested: during NSM Meeting on June 15th 

Solves the problem(s):
- find a time that will work best for the group, including 8-9am PT (current time)
- use a voting method that allows voters to "give weight" to their preferred meeting time

Tasks: 
- [x]   review results and options from previous poll https://docs.google.com/forms/d/e/1FAIpQLSdX7jjPn0AfEoCENVWLwI44fOuT7U_imLtYbsQvaGM7bqf-1Q/viewform

- [x]   create a new google form to allow each voter to use up to x votes

- [x]   use Pacific Time for meeting time options

- [x]   send URL to poll to mailing list for networkservicemesh: networkservicemesh@googlegroups.com

**Comment by lixuna** [comment]
Ready for peer review:  https://goo.gl/forms/s3DwCAgncieoYZYE3

**Comment by edwarnicke** [comment]
I love that we get a prime number of points to spend :)

Ed


On June 15, 2018 at 12:16:24 PM, Lucina (notifications@github.com) wrote:

Ready for peer review: https://goo.gl/forms/s3DwCAgncieoYZYE3

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ligato/networkservicemesh/issues/97#issuecomment-397686889>,
or mute the thread

**Comment by lixuna** [comment]
I reused the time options from the original poll: https://docs.google.com/forms/d/e/1FAIpQLSdX7jjPn0AfEoCENVWLwI44fOuT7U_imLtYbsQvaGM7bqf-1Q/formResponse

Seeing the low results for the latest times (9pm Pacific), I'll remove those options and add more AM options.

**Comment by lixuna** [comment]
Being mindful of the CNCF Public Events Calendar, I added more AM Pacific Time options. 8 options, 8 votes per person.

Updated Draft, ready for peer review: https://goo.gl/forms/s3DwCAgncieoYZYE3

**Comment by edwarnicke** [comment]
Many thanks!

Folks, lets get responses to the poll so we can work out meeting times :)

Ed


On June 15, 2018 at 12:54:22 PM, Lucina (notifications@github.com) wrote:

Being mindful of the CNCF Public Events Calendar, I added more AM Pacific
Time options. 8 options, 8 votes per person.

Updated Draft, ready for peer review: https://goo.gl/forms/s3DwCAgncieoYZYE3

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ligato/networkservicemesh/issues/97#issuecomment-397696955>,
or mute the thread

**Comment by lixuna** [comment]
Update: email sent to networkservicemesh@googlegroups.com

**Comment by taylor** [comment]
Top 3 day/times:
1. Friday, 8am Pacific
2. Tuesday, 7am Pacific
3. Wednesday, 7am Pacific

Action items:
- Stay with Friday at 8am Pacific
- Review in a few months

**Comment by mestery** [comment]
Closing this now, we decided to keep the current meeting time and revisit in the fall.
